[package]
name = "anychain"
version = "0.0.1"
edition = "2021"
description = "A Rust library for multi-chain cryptowallet, support Bitcoin, Ethereum, Tron, Filecoin, etc"
repository = "https://github.com/uduncloud/anychain"
keywords = ["multi-chain", "cryptocurrency", "bitcoin", "ethereum"]

[lib]
path = "lib.rs"

[dependencies]
anychain-core = { path ="./anychain-core" }
anychain-bitcoin = { path = "./anychain-bitcoin" }
anychain-bitcoincash = { path = "./anychain-bitcoincash" }
anychain-ethereum = { path = "./anychain-ethereum" }
anychain-tron = { path = "./anychain-tron" }
anychain-filecoin = { path = "./anychain-filecoin" }
anychain-polkadot = { path = "./anychain-polkadot" }

[workspace]
members = [
    "anychain-core",
    "anychain-bitcoin",
    "anychain-bitcoin-client",
    "anychain-bitcoincash",
    "anychain-ethereum",
    "anychain-tron",
    "anychain-filecoin",
    "anychain-polkadot",
]

[profile.release]
debug = true
lto = true
codegen-units = 1
