// This file is @generated by prost-build.

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShardId {
    #[prost(int64, tag = "1")]
    pub shard_num: i64,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RealmId {
    #[prost(int64, tag = "1")]
    pub shard_num: i64,
    #[prost(int64, tag = "2")]
    pub realm_num: i64,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountId {
    #[prost(int64, tag = "1")]
    pub shard_num: i64,
    #[prost(int64, tag = "2")]
    pub realm_num: i64,
    #[prost(oneof = "account_id::Account", tags = "3, 4")]
    pub account: ::core::option::Option<account_id::Account>,
}

pub mod account_id {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Account {
        #[prost(int64, tag = "3")]
        AccountNum(i64),
        #[prost(bytes = "vec", tag = "4")]
        Alias(::prost::alloc::vec::Vec<u8>),
    }
}

#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Duration {
    #[prost(int64, tag = "1")]
    pub seconds: i64,
}

#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Timestamp {
    #[prost(int64, tag = "1")]
    pub seconds: i64,
    #[prost(int32, tag = "2")]
    pub nanos: i32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionId {
    #[prost(message, optional, tag = "1")]
    pub transaction_valid_start: ::core::option::Option<Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub account_id: ::core::option::Option<AccountId>,
    #[prost(bool, tag = "3")]
    pub scheduled: bool,
    #[prost(int32, tag = "4")]
    pub nonce: i32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Key {
    #[prost(oneof = "key::Key", tags = "2, 7")]
    pub key: ::core::option::Option<key::Key>,
}

pub mod key {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Key {
        #[prost(bytes = "vec", tag = "2")]
        Ed25519(::prost::alloc::vec::Vec<u8>),
        #[prost(bytes = "vec", tag = "7")]
        EcdsaSecp256k1(::prost::alloc::vec::Vec<u8>),
    }
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoCreateTransactionBody {
    #[prost(message, optional, tag = "1")]
    pub key: ::core::option::Option<Key>,
    #[prost(uint64, tag = "2")]
    pub initial_balance: u64,
    #[prost(bool, tag = "11")]
    pub receiver_sig_required: bool,
    #[prost(message, optional, tag = "13")]
    pub auto_renew_period: ::core::option::Option<Duration>,
    #[prost(string, tag = "16")]
    pub memo: ::prost::alloc::string::String,
    #[prost(int32, tag = "18")]
    pub max_automatic_token_associations: i32,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountAmount {
    #[prost(message, optional, tag = "1")]
    pub account_id: ::core::option::Option<AccountId>,
    #[prost(sint64, tag = "2")]
    pub amount: i64,
    #[prost(bool, tag = "3")]
    pub is_approval: bool,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferList {
    #[prost(message, repeated, tag = "1")]
    pub account_amounts: ::prost::alloc::vec::Vec<AccountAmount>,
}

#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TokenId {
    #[prost(int64, tag = "1")]
    pub shard_num: i64,
    #[prost(int64, tag = "2")]
    pub realm_num: i64,
    #[prost(int64, tag = "3")]
    pub token_num: i64,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenTransferList {
    #[prost(message, optional, tag = "1")]
    pub token: ::core::option::Option<TokenId>,
    #[prost(message, repeated, tag = "2")]
    pub transfers: ::prost::alloc::vec::Vec<AccountAmount>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoTransferTransactionBody {
    #[prost(message, optional, tag = "1")]
    pub transfers: ::core::option::Option<TransferList>,
    #[prost(message, repeated, tag = "2")]
    pub token_transfers: ::prost::alloc::vec::Vec<TokenTransferList>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionBody {
    #[prost(message, optional, tag = "1")]
    pub transaction_id: ::core::option::Option<TransactionId>,
    #[prost(message, optional, tag = "2")]
    pub node_account_id: ::core::option::Option<AccountId>,
    #[prost(uint64, tag = "3")]
    pub transaction_fee: u64,
    #[prost(message, optional, tag = "4")]
    pub transaction_valid_duration: ::core::option::Option<Duration>,
    #[prost(bool, tag = "5")]
    pub generate_record: bool,
    #[prost(string, tag = "6")]
    pub memo: ::prost::alloc::string::String,
    #[prost(oneof = "transaction_body::Data", tags = "11, 14")]
    pub data: ::core::option::Option<transaction_body::Data>,
}

pub mod transaction_body {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "11")]
        CryptoCreateAccount(super::CryptoCreateTransactionBody),
        #[prost(message, tag = "14")]
        CryptoTransfer(super::CryptoTransferTransactionBody),
    }
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignaturePair {
    #[prost(bytes = "vec", tag = "1")]
    pub pub_key_prefix: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "signature_pair::Signature", tags = "3, 6")]
    pub signature: ::core::option::Option<signature_pair::Signature>,
}

pub mod signature_pair {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Signature {
        #[prost(bytes = "vec", tag = "3")]
        Ed25519(::prost::alloc::vec::Vec<u8>),
        #[prost(bytes = "vec", tag = "6")]
        EcdsaSecp256k1(::prost::alloc::vec::Vec<u8>),
    }
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignatureMap {
    #[prost(message, repeated, tag = "1")]
    pub sig_pair: ::prost::alloc::vec::Vec<SignaturePair>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignedTransaction {
    #[prost(bytes = "vec", tag = "1")]
    pub body_bytes: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub sig_map: ::core::option::Option<SignatureMap>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes = "vec", tag = "5")]
    pub signed_transaction_bytes: ::prost::alloc::vec::Vec<u8>,
}

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionResponse {
    #[prost(int32, tag = "1")]
    pub node_transaction_precheck_code: i32,
    #[prost(uint64, tag = "2")]
    pub cost: u64,
}

/// A simple protobuf wrapper to store a list of transactions. This is used by
/// `Transaction.[from|to]Bytes()` in the SDKs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionList {
    #[prost(message, repeated, tag = "1")]
    pub transaction_list: ::prost::alloc::vec::Vec<Transaction>,
}
