// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ConsensusTopicQuery {
    /// *
    /// A required topic ID to retrieve messages for.
    #[prost(message, optional, tag = "1")]
    pub topic_id: ::core::option::Option<crate::services::TopicId>,
    /// *
    /// Include messages which reached consensus on or after this time. Defaults to current time if
    /// not set.
    #[prost(message, optional, tag = "2")]
    pub consensus_start_time: ::core::option::Option<crate::services::Timestamp>,
    /// *
    /// Include messages which reached consensus before this time. If not set it will receive
    /// indefinitely.
    #[prost(message, optional, tag = "3")]
    pub consensus_end_time: ::core::option::Option<crate::services::Timestamp>,
    /// *
    /// The maximum number of messages to receive before stopping. If not set or set to zero it will
    /// return messages indefinitely.
    #[prost(uint64, tag = "4")]
    pub limit: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConsensusTopicResponse {
    /// *
    /// The time at which the transaction reached consensus
    #[prost(message, optional, tag = "1")]
    pub consensus_timestamp: ::core::option::Option<crate::services::Timestamp>,
    /// *
    /// The message body originally in the ConsensusSubmitMessageTransactionBody. Message size will
    /// be less than 6KiB.
    #[prost(bytes = "vec", tag = "2")]
    pub message: ::prost::alloc::vec::Vec<u8>,
    /// *
    /// The running hash (SHA384) of every message.
    #[prost(bytes = "vec", tag = "3")]
    pub running_hash: ::prost::alloc::vec::Vec<u8>,
    /// *
    /// Starts at 1 for first submitted message. Incremented on each submitted message.
    #[prost(uint64, tag = "4")]
    pub sequence_number: u64,
    /// *
    /// Version of the SHA-384 digest used to update the running hash.
    #[prost(uint64, tag = "5")]
    pub running_hash_version: u64,
    /// *
    /// Optional information of the current chunk in a fragmented message.
    #[prost(message, optional, tag = "6")]
    pub chunk_info: ::core::option::Option<crate::services::ConsensusMessageChunkInfo>,
}
/// Generated client implementations.
pub mod consensus_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// *
    /// The Mirror Service provides the ability to query a stream of Hedera Consensus Service (HCS)
    /// messages for an HCS Topic via a specific (possibly open-ended) time range.
    #[derive(Debug, Clone)]
    pub struct ConsensusServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ConsensusServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ConsensusServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ConsensusServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ConsensusServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn subscribe_topic(
            &mut self,
            request: impl tonic::IntoRequest<super::ConsensusTopicQuery>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ConsensusTopicResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/com.hedera.mirror.api.proto.ConsensusService/subscribeTopic",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "com.hedera.mirror.api.proto.ConsensusService",
                        "subscribeTopic",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// *
/// Request object to query an address book for its list of nodes
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AddressBookQuery {
    /// *
    /// The ID of the address book file on the network. Can be either 0.0.101 or 0.0.102.
    #[prost(message, optional, tag = "1")]
    pub file_id: ::core::option::Option<crate::services::FileId>,
    /// *
    /// The maximum number of node addresses to receive before stopping. If not set or set to zero it will return all node addresses in the database.
    #[prost(int32, tag = "2")]
    pub limit: i32,
}
/// Generated client implementations.
pub mod network_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// *
    /// Provides cross network APIs like address book queries
    #[derive(Debug, Clone)]
    pub struct NetworkServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl NetworkServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> NetworkServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> NetworkServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            NetworkServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        ///
        /// Query for an address book and return its nodes. The nodes are returned in ascending order by node ID. The
        /// response is not guaranteed to be a byte-for-byte equivalent to the NodeAddress in the Hedera file on
        /// the network since it is reconstructed from a normalized database table.
        pub async fn get_nodes(
            &mut self,
            request: impl tonic::IntoRequest<super::AddressBookQuery>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<crate::services::NodeAddress>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/com.hedera.mirror.api.proto.NetworkService/getNodes",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "com.hedera.mirror.api.proto.NetworkService",
                        "getNodes",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
