// This file is @generated by prost-build.
/// An identifier for a unique token (or "NFT"), used by both contract
/// and token services.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NftId {
        /// A token identifier.<br/>
    /// This token represents the collection containing this NFT.
    #[prost(message, optional, tag = "1")]
    pub token_id: ::core::option::Option<crate::services::TokenId>,
        /// A unique serial number.<br/>
    /// This serial number is unique within its token type.
    #[prost(int64, tag = "2")]
    pub serial_number: i64,
}
/// Once a hook is created, its full id.
/// <p>
/// A composite of its creating entity's id and an arbitrary 64-bit hook id
/// (which need not be sequential).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HookId {
        /// The hook's creating entity id.
    #[prost(message, optional, tag = "1")]
    pub entity_id: ::core::option::Option<HookEntityId>,
        /// An arbitrary 64-bit identifier.
    #[prost(int64, tag = "2")]
    pub hook_id: i64,
}
/// The id of an entity using a hook.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HookEntityId {
    #[prost(oneof = "hook_entity_id::EntityId", tags = "1, 2")]
    pub entity_id: ::core::option::Option<hook_entity_id::EntityId>,
}
/// Nested message and enum types in `HookEntityId`.
pub mod hook_entity_id {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum EntityId {
                /// An account using a hook.
        #[prost(message, tag = "1")]
        AccountId(crate::services::AccountId),
                /// A contract using a hook.
        #[prost(message, tag = "2")]
        ContractId(crate::services::ContractId),
    }
}
/// Specifies a call to a hook from within a transaction.
/// <p>
/// Often the hook's entity is implied by the nature of the call site. For example, when using an account allowance hook
/// inside a crypto transfer, the hook's entity is necessarily the account whose authorization is required.
/// <p>
/// For future extension points where the hook owner is not forced by the context, we include the option to fully
/// specify the hook id for the call.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HookCall {
    #[prost(oneof = "hook_call::Id", tags = "1")]
    pub id: ::core::option::Option<hook_call::Id>,
        /// Specifies details of the call.
    #[prost(oneof = "hook_call::CallSpec", tags = "3")]
    pub call_spec: ::core::option::Option<hook_call::CallSpec>,
}
/// Nested message and enum types in `HookCall`.
pub mod hook_call {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Id {
                /// The numeric id of the hook to call, when the owning entity is forced by the call site.
        #[prost(int64, tag = "1")]
        HookId(i64),
    }
        /// Specifies details of the call.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum CallSpec {
                /// Specification of how to call an EVM hook.
        #[prost(message, tag = "3")]
        EvmHookCall(super::EvmHookCall),
    }
}
/// Specifies details of a call to an EVM hook.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvmHookCall {
        /// Call data to pass to the hook via the IHieroHook.HookContext#data field.
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
        /// The gas limit to use.
    #[prost(uint64, tag = "2")]
    pub gas_limit: u64,
}
/// A unique, composite, identifier for a pending airdrop.
///
/// Each pending airdrop SHALL be uniquely identified by
/// a `PendingAirdropId`.<br/>
/// A `PendingAirdropId` SHALL be recorded when created and MUST be provided in
/// any transaction that would modify that pending airdrop
/// (such as a `claimAirdrop` or `cancelAirdrop`).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PendingAirdropId {
        /// A sending account.
    /// <p>
    /// This is the account that initiated, and SHALL fund,
    /// this pending airdrop.<br/>
    /// This field is REQUIRED.
    #[prost(message, optional, tag = "1")]
    pub sender_id: ::core::option::Option<crate::services::AccountId>,
        /// A receiving account.
    /// <p>
    /// This is the ID of the account that SHALL receive the airdrop.<br/>
    /// This field is REQUIRED.
    #[prost(message, optional, tag = "2")]
    pub receiver_id: ::core::option::Option<crate::services::AccountId>,
    #[prost(oneof = "pending_airdrop_id::TokenReference", tags = "3, 4")]
    pub token_reference: ::core::option::Option<pending_airdrop_id::TokenReference>,
}
/// Nested message and enum types in `PendingAirdropId`.
pub mod pending_airdrop_id {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum TokenReference {
                /// A token identifier.<br/>
        /// This is the type of token for a fungible/common token airdrop.
        /// <p>
        /// This field is REQUIRED for a fungible/common token and MUST NOT
        /// be used for a non-fungible/unique token.
        #[prost(message, tag = "3")]
        FungibleTokenType(crate::services::TokenId),
                /// The id of a single NFT<br/>
        /// This is the type of token for a non-fungible/unique token airdrop
        /// and consists of a Token ID and serial number.
        /// <p>
        /// This field is REQUIRED for a non-fungible/unique token and
        /// MUST NOT be used for a fungible/common token.
        #[prost(message, tag = "4")]
        NonFungibleToken(super::NftId),
    }
}
/// A single pending airdrop value.
///
/// This message SHALL record the airdrop amount for a
/// fungible/common token.<br/>
/// This message SHOULD be null for a non-fungible/unique token.<br/>
/// If a non-null `PendingAirdropValue` is set for a non-fungible/unique
/// token, the amount field MUST be `0`.
///
/// It is RECOMMENDED that implementations store pending airdrop information
/// as a key-value map from `PendingAirdropId` to `PendingAirdropValue`, with
/// a `null` value used for non-fungible pending airdrops.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PendingAirdropValue {
        /// An amount to transfer for fungible/common tokens.<br/>
    /// This is expressed in the smallest available units for that token
    /// (i.e. 10<sup>-`decimals`</sup> whole tokens).
    /// <p>
    /// This amount SHALL be transferred from the sender to the receiver,
    /// if claimed.<br/>
    /// If the token is a fungible/common token, this value MUST be strictly
    /// greater than `0`.<br/>
    /// If the token is a non-fungible/unique token, this message SHOULD NOT
    /// be set, and if set, this field MUST be `0`.
    #[prost(uint64, tag = "1")]
    pub amount: u64,
}
/// A specific hash algorithm.
///
/// We did not reuse Record Stream `HashAlgorithm` here because in all cases,
/// currently, this will be `SHA2_384` and if that is the default value then
/// we can save space by not serializing it, whereas `HASH_ALGORITHM_UNKNOWN`
/// is the default for Record Stream `HashAlgorithm`.
///
/// Note that enum values here MUST NOT match the name of any other enum value
/// in the same `package`, as protobuf follows `C++` scope rules and all enum
/// _names_ are treated as global constants within the `package`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BlockHashAlgorithm {
        /// A SHA2 algorithm SHA-384 hash.
    /// <p>
    /// This is the default value, if a field of this enumerated type is
    /// not set, then this is the value that will be decoded when the
    /// serialized message is read.
    Sha2384 = 0,
}
impl BlockHashAlgorithm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Sha2384 => "SHA2_384",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SHA2_384" => Some(Self::Sha2384),
            _ => None,
        }
    }
}
/// Types of validation strategies for token keys.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TokenKeyValidation {
        /// Perform all token key validations.<br/>
    /// This is the default value and behavior.
    FullValidation = 0,
        /// Perform no validations at all for all passed token keys.
    NoValidation = 1,
}
impl TokenKeyValidation {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::FullValidation => "FULL_VALIDATION",
            Self::NoValidation => "NO_VALIDATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FULL_VALIDATION" => Some(Self::FullValidation),
            "NO_VALIDATION" => Some(Self::NoValidation),
            _ => None,
        }
    }
}
/// Specifies the creation of a new hook at the given id for the given entity.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HookCreation {
        /// The id of the hook's entity.
    #[prost(message, optional, tag = "1")]
    pub entity_id: ::core::option::Option<HookEntityId>,
        /// The creation details.
    #[prost(message, optional, tag = "2")]
    pub details: ::core::option::Option<HookCreationDetails>,
        /// If set, the id of the hook following this one in the owner's
    /// doubly-linked list of hooks.
    #[prost(message, optional, tag = "9")]
    pub next_hook_id: ::core::option::Option<i64>,
}
/// **
/// The details of a hook's creation.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HookCreationDetails {
        /// The extension point for the hook.
    #[prost(enumeration = "HookExtensionPoint", tag = "1")]
    pub extension_point: i32,
        /// The id to create the hook at.
    #[prost(int64, tag = "2")]
    pub hook_id: i64,
        /// If set, a key that that can be used to remove or replace the hook; or (if
    /// applicable, as with an EVM hook) do transactions that customize the hook.
    #[prost(message, optional, tag = "4")]
    pub admin_key: ::core::option::Option<crate::services::Key>,
        /// The hook implementation.
    #[prost(oneof = "hook_creation_details::Hook", tags = "3")]
    pub hook: ::core::option::Option<hook_creation_details::Hook>,
}
/// Nested message and enum types in `HookCreationDetails`.
pub mod hook_creation_details {
        /// The hook implementation.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Hook {
                /// A general-purpose hook programmed in EVM bytecode that may access state
        /// or interact with external contracts.
        #[prost(message, tag = "3")]
        EvmHook(super::EvmHook),
    }
}
/// Definition of a general-purpose EVM hook.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvmHook {
        /// The specification for the hook.
    #[prost(message, optional, tag = "1")]
    pub spec: ::core::option::Option<EvmHookSpec>,
        /// Initial storage updates for the hook, if any.
    #[prost(message, repeated, tag = "2")]
    pub storage_updates: ::prost::alloc::vec::Vec<EvmHookStorageUpdate>,
}
/// Shared specifications for an EVM hook. May be used for any extension point.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvmHookSpec {
        /// The source of the EVM bytecode for the hook.
    #[prost(oneof = "evm_hook_spec::BytecodeSource", tags = "1")]
    pub bytecode_source: ::core::option::Option<evm_hook_spec::BytecodeSource>,
}
/// Nested message and enum types in `EvmHookSpec`.
pub mod evm_hook_spec {
        /// The source of the EVM bytecode for the hook.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum BytecodeSource {
                /// The id of a contract that implements the extension point API with EVM bytecode.
        #[prost(message, tag = "1")]
        ContractId(crate::services::ContractId),
    }
}
/// Specifies a key/value pair in the storage of an EVM hook, either by the explicit storage
/// slot contents; or by a combination of a Solidity mapping's slot key and the key into
/// that mapping.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvmHookStorageUpdate {
    #[prost(oneof = "evm_hook_storage_update::Update", tags = "1, 2")]
    pub update: ::core::option::Option<evm_hook_storage_update::Update>,
}
/// Nested message and enum types in `EvmHookStorageUpdate`.
pub mod evm_hook_storage_update {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Update {
                /// An explicit storage slot update.
        #[prost(message, tag = "1")]
        StorageSlot(super::EvmHookStorageSlot),
                /// Implicit storage slot updates specified as Solidity mapping entries.
        #[prost(message, tag = "2")]
        MappingEntries(super::EvmHookMappingEntries),
    }
}
/// Specifies storage slot updates via indirection into a Solidity mapping.
/// <p>
/// Concretely, if the Solidity mapping is itself at slot `mapping_slot`, then
/// the * storage slot for key `key` in the mapping is defined by the relationship
/// `key_storage_slot = keccak256(abi.encodePacked(mapping_slot, key))`.
/// <p>
/// This message lets a metaprotocol be specified in terms of changes to a
/// Solidity mapping's entries. If only raw slots could be updated, then a block
/// stream consumer following the metaprotocol would have to invert the Keccak256
/// hash to determine which mapping entry was being updated, which is not possible.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvmHookMappingEntries {
        /// The slot that corresponds to the Solidity mapping itself. Must use a
    /// minimal byte representation (no leading zeros).
    #[prost(bytes = "vec", tag = "1")]
    pub mapping_slot: ::prost::alloc::vec::Vec<u8>,
        /// The entries in the mapping at the given slot.
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<EvmHookMappingEntry>,
}
/// An entry in a Solidity mapping. Very helpful for protocols that apply
/// `HookStore` to manage the entries of a hook contract's mapping instead
/// its raw storage slots.
/// <p>
/// This is especially attractive when the mapping value itself fits in a single
/// word; for more complicated value storage layouts it becomes necessary to
/// combine the mapping update with additional `EvmHookStorageSlot` updates that
/// specify the complete storage slots of the value type.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvmHookMappingEntry {
        /// If the mapping entry is present and non-zero, its value. May not be longer than
    /// 32 bytes in length; must use a minimal byte representation (no leading zeros).
    /// Leaving this field empty in an update removes the entry from the mapping.
    #[prost(bytes = "vec", tag = "3")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "evm_hook_mapping_entry::EntryKey", tags = "1, 2")]
    pub entry_key: ::core::option::Option<evm_hook_mapping_entry::EntryKey>,
}
/// Nested message and enum types in `EvmHookMappingEntry`.
pub mod evm_hook_mapping_entry {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum EntryKey {
                /// The explicit bytes of the mapping entry. Must use a minimal byte representation;
        /// may not exceed 32 bytes in length.
        #[prost(bytes, tag = "1")]
        Key(::prost::alloc::vec::Vec<u8>),
                /// The bytes that are the preimage of the Keccak256 hash that forms the mapping key.
        /// May be longer or shorter than 32 bytes and may have leading zeros, since Solidity
        /// supports variable-length keys in mappings.
        #[prost(bytes, tag = "2")]
        Preimage(::prost::alloc::vec::Vec<u8>),
    }
}
/// A slot in the storage of an EVM hook.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvmHookStorageSlot {
        /// The key of the slot. Must use a minimal byte representation (no
    /// leading zeros); may not exceed 32 bytes in length.
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
        /// If the slot is present and non-zero, its value. Must use a minimal
    /// byte representation (no leading zeros); may not exceed 32 bytes in
    /// length Leaving this field empty in an update removes the slot from
    /// storage.
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
/// **
/// The Hiero extension points that accept a hook.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum HookExtensionPoint {
        /// Used to customize an account's allowances during a CryptoTransfer transaction.
    AccountAllowanceHook = 0,
}
impl HookExtensionPoint {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AccountAllowanceHook => "ACCOUNT_ALLOWANCE_HOOK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACCOUNT_ALLOWANCE_HOOK" => Some(Self::AccountAllowanceHook),
            _ => None,
        }
    }
}
/// A custom fee definition for a consensus topic.
/// <p>
/// This fee definition is specific to an Hedera Consensus Service (HCS) topic
/// and SHOULD NOT be used in any other context.<br/>
/// All fields for this message are REQUIRED.<br/>
/// Only "fixed" fee definitions are supported because there is no basis for
/// a fractional fee on a consensus submit transaction.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FixedCustomFee {
        /// A fixed custom fee.
    /// <p>
    /// The amount of HBAR or other token described by this `FixedFee` SHALL
    /// be charged to the transction payer for each message submitted to a
    /// topic that assigns this consensus custom fee.
    #[prost(message, optional, tag = "1")]
    pub fixed_fee: ::core::option::Option<crate::services::FixedFee>,
        /// A collection account identifier.
    /// <p>
    /// All amounts collected for this consensus custom fee SHALL be transferred
    /// to the account identified by this field.
    #[prost(message, optional, tag = "2")]
    pub fee_collector_account_id: ::core::option::Option<crate::services::AccountId>,
}
/// A wrapper around a consensus custom fee list.<br/>
/// This wrapper exists to enable an update transaction to differentiate between
///   a field that is not set and an empty list of custom fees.
/// <p>
/// An _unset_ field of this type SHALL NOT modify existing values.<br/>
/// A _set_ field of this type with an empty `fees` list SHALL remove any
///   existing values.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FixedCustomFeeList {
        /// A set of custom fee definitions.<br/>
    /// These are fees to be assessed for each submit to a topic.
    #[prost(message, repeated, tag = "1")]
    pub fees: ::prost::alloc::vec::Vec<FixedCustomFee>,
}
/// A wrapper for fee exempt key list.<br/>
/// This wrapper exists to enable an update transaction to differentiate between
/// a field that is not set and an empty list of keys.
/// <p>
/// An _unset_ field of this type SHALL NOT modify existing values.<br/>
/// A _set_ field of this type with an empty `keys` list SHALL remove any
/// existing values.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeExemptKeyList {
        /// A set of keys.<br/>
    /// The keys in this list are permitted to submit messages to the
    /// topic without paying the topic's custom fees.
    /// <p>
    /// If a submit transaction is signed by _any_ key included in this set,
    /// custom fees SHALL NOT be charged for that transaction.
    #[prost(message, repeated, tag = "1")]
    pub keys: ::prost::alloc::vec::Vec<crate::services::Key>,
}
/// A maximum custom fee that the user is willing to pay.
/// <p>
/// This message is used to specify the maximum custom fee that given user is
/// willing to pay.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CustomFeeLimit {
        /// A payer account identifier.
    #[prost(message, optional, tag = "1")]
    pub account_id: ::core::option::Option<crate::services::AccountId>,
        /// The maximum fees that the user is willing to pay for the message.
    #[prost(message, repeated, tag = "2")]
    pub fees: ::prost::alloc::vec::Vec<crate::services::FixedFee>,
}
/// Reject undesired token(s).<br/>
/// Transfer one or more token balances held by the requesting account to the
/// treasury for each token type.
///
/// Each transfer SHALL be one of the following
/// - A single non-fungible/unique token.
/// - The full balance held for a fungible/common token.
/// A single `tokenReject` transaction SHALL support a maximum
/// of 10 transfers.<br/>
/// A token that is `pause`d MUST NOT be rejected.<br/>
/// If the `owner` account is `frozen` with respect to the identified token(s)
/// the token(s) MUST NOT be rejected.<br/>
/// The `payer` for this transaction, and `owner` if set, SHALL NOT be charged
/// any custom fees or other fees beyond the `tokenReject` transaction fee.
///
/// ### Block Stream Effects
/// - Each successful transfer from `payer` to `treasury` SHALL be recorded in
///    the `token_transfer_list` for the transaction record.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenRejectTransactionBody {
        /// An account identifier.<br/>
    /// This OPTIONAL field identifies the account holding the
    /// tokens to be rejected.
    /// <p>
    /// If set, this account MUST sign this transaction.
    /// If not set, the `payer` for this transaction SHALL be the effective
    /// `owner` for this transaction.
    #[prost(message, optional, tag = "1")]
    pub owner: ::core::option::Option<crate::services::AccountId>,
        /// A list of one or more token rejections.
    /// <p>
    /// On success each rejected token serial number or balance SHALL be
    /// transferred from the requesting account to the treasury account for
    /// that token type.<br/>
    /// After rejection the requesting account SHALL continue to be associated
    /// with the token.<br/>
    /// If dissociation is desired then a separate `TokenDissociate` transaction
    /// MUST be submitted to remove the association.<br/>
    /// This list MUST contain at least one (1) entry and MUST NOT contain more
    /// than ten (10) entries.
    #[prost(message, repeated, tag = "2")]
    pub rejections: ::prost::alloc::vec::Vec<TokenReference>,
}
/// A union token identifier.
///
/// Identify a fungible/common token type, or a single
/// non-fungible/unique token serial.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TokenReference {
    #[prost(oneof = "token_reference::TokenIdentifier", tags = "1, 2")]
    pub token_identifier: ::core::option::Option<token_reference::TokenIdentifier>,
}
/// Nested message and enum types in `TokenReference`.
pub mod token_reference {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum TokenIdentifier {
                /// A fungible/common token type.
        #[prost(message, tag = "1")]
        FungibleToken(crate::services::TokenId),
                /// A single specific serialized non-fungible/unique token.
        #[prost(message, tag = "2")]
        Nft(super::NftId),
    }
}
/// Airdrop one or more tokens to one or more accounts.
///
/// ### Effects
/// This distributes tokens from the balance of one or more sending account(s)
/// to the balance of one or more recipient accounts. Accounts MAY receive the
/// tokens in one of four ways.
///
///   - An account already associated to the token to be distributed SHALL
///     receive the airdropped tokens immediately to the recipient account
///     balance.<br/>
///     The fee for this transfer SHALL include the transfer, the airdrop fee,
///     and any custom fees.
///   - An account with available automatic association slots SHALL be
///     automatically associated to the token, and SHALL immediately receive
///     the airdropped tokens to the recipient account balance.<br/>
///     The fee for this transfer SHALL include the transfer, the association,
///     the cost to renew that association once, the airdrop fee, and
///     any custom fees.
///   - An account with "receiver signature required" set SHALL have a
///     "Pending Airdrop" created and must claim that airdrop with a
///     `claimAirdrop` transaction.<br/>
///     The fee for this transfer SHALL include the transfer, the association,
///     the cost to renew that association once, the airdrop fee, and
///     any custom fees.<br/>
///     If the pending airdrop is not claimed immediately, the `sender` SHALL
///     pay the cost to renew the token association, and the cost to maintain
///     the pending airdrop, until the pending airdrop is claimed or cancelled.
///   - An account with no available automatic association slots SHALL have a
///     "Pending Airdrop" created and must claim that airdrop with a
///     `claimAirdrop` transaction.<br/>
///     The fee for this transfer SHALL include the transfer, the association,
///     the cost to renew that association once, the airdrop fee, and any custom
///     fees.<br/>
///     If the pending airdrop is not claimed immediately, the `sender` SHALL
///     pay the cost to renew the token association, and the cost to maintain
///     the pending airdrop, until the pending airdrop is claimed or cancelled.
///
/// If an airdrop would create a pending airdrop for a fungible/common token,
/// and a pending airdrop for the same sender, receiver, and token already
/// exists, the existing pending airdrop SHALL be updated to add the new
/// amount to the existing airdrop, rather than creating
/// a new pending airdrop.<br/>
/// Any airdrop that completes immediately SHALL be irreversible. Any airdrop
/// that results in a "Pending Airdrop" MAY be canceled via a `cancelAirdrop`
/// transaction.<br/>
/// All transfer fees (including custom fees and royalties), as well as the
/// rent cost for the first auto-renewal period for any automatic-association
/// slot occupied by the airdropped tokens, SHALL be charged to the account
/// paying for this transaction.<br/>
///
/// ### Block Stream Effects
/// - Each successful transfer SHALL be recorded in `token_transfer_list`
///    for the transaction record.
/// - Each successful transfer that consumes an automatic association slot
///    SHALL populate the `automatic_association` field for the record.
/// - Each pending transfer _created_ SHALL be added to the
///    `pending_airdrops` field for the record.
/// - Each pending transfer _updated_ SHALL be added to the
///    `pending_airdrops` field for the record.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenAirdropTransactionBody {
        /// A list of token transfers representing one or more airdrops.
    /// <p>
    /// The sender for each transfer MUST have sufficient balance to complete
    /// the transfers.<br/>
    /// All token transfers MUST successfully transfer tokens or create a
    /// pending airdrop for this transaction to succeed.<br/>
    /// This list MUST contain between 1 and 10 transfers, inclusive.
    /// <p>
    /// Note that each transfer of fungible/common tokens requires both a debit
    /// and a credit, so each _fungible_ token transfer MUST have _balanced_
    /// entries in the TokenTransferList for that transfer.
    #[prost(message, repeated, tag = "1")]
    pub token_transfers: ::prost::alloc::vec::Vec<crate::services::TokenTransferList>,
}
/// Token cancel airdrop<br/>
/// Remove one or more pending airdrops from state on behalf of the
/// sender(s) for each airdrop.
///
/// Each pending airdrop canceled SHALL be removed from state and
/// SHALL NOT be available to claim.<br/>
/// Each cancellation SHALL be represented in the transaction body and
/// SHALL NOT be restated in the record file.<br/>
/// All cancellations MUST succeed for this transaction to succeed.
///
/// ### Block Stream Effects
/// None
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenCancelAirdropTransactionBody {
        /// A list of one or more pending airdrop identifiers.<br/>
    /// This list declares the set of pending airdrop entries that the client
    /// wishes to cancel; on success all listed pending airdrop entries
    /// will be removed.
    /// <p>
    /// This transaction MUST be signed by the account identified by a
    /// `sender_id` for each entry in this list.<br/>
    /// This list MUST NOT have any duplicate entries.<br/>
    /// This list MUST contain between 1 and 10 entries, inclusive.
    #[prost(message, repeated, tag = "1")]
    pub pending_airdrops: ::prost::alloc::vec::Vec<PendingAirdropId>,
}
/// Token claim airdrop<br/>
/// Complete one or more pending transfers on behalf of the
/// recipient(s) for an airdrop.
///
/// The sender MUST have sufficient balance to fulfill the airdrop at the
/// time of claim. If the sender does not have sufficient balance, the
/// claim SHALL fail.<br/>
/// Each pending airdrop successfully claimed SHALL be removed from state and
/// SHALL NOT be available to claim again.<br/>
/// Each claim SHALL be represented in the transaction body and
/// SHALL NOT be restated in the record file.<br/>
/// All claims MUST succeed for this transaction to succeed.
///
/// ### Block Stream Effects
/// The completed transfers SHALL be present in the transfer list.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenClaimAirdropTransactionBody {
        /// A list of one or more pending airdrop identifiers.
    /// <p>
    /// This transaction MUST be signed by the account identified by
    /// the `receiver_id` for each entry in this list.<br/>
    /// This list MUST contain between 1 and 10 entries, inclusive.<br/>
    /// This list MUST NOT have any duplicate entries.
    #[prost(message, repeated, tag = "1")]
    pub pending_airdrops: ::prost::alloc::vec::Vec<PendingAirdropId>,
}
/// A transaction body to add a new consensus node to the network address book.
///
/// This transaction body SHALL be considered a "privileged transaction".
///
/// This message supports a transaction to create a new node in the network
/// address book. The transaction, once complete, enables a new consensus node
/// to join the network, and requires governing council authorization.
///
/// - A `NodeCreateTransactionBody` MUST be signed by the `Key` assigned to the
///    `admin_key` field and one of those keys: treasure account (2) key,
///    systemAdmin(50) key, or addressBookAdmin(55) key.
/// - The newly created node information SHALL be added to the network address
///    book information in the network state.
/// - The new entry SHALL be created in "state" but SHALL NOT participate in
///    network consensus and SHALL NOT be present in network "configuration"
///    until the next "upgrade" transaction (as noted below).
/// - All new address book entries SHALL be added to the active network
///    configuration during the next `freeze` transaction with the field
///    `freeze_type` set to `PREPARE_UPGRADE`.
///
/// ### Block Stream Effects
/// Upon completion the newly assigned `node_id` SHALL be recorded in
/// the transaction receipt.<br/>
/// This value SHALL be the next available node identifier.<br/>
/// Node identifiers SHALL NOT be reused.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeCreateTransactionBody {
        /// A Node account identifier.
    /// <p>
    /// This account identifier MUST be in the "account number" form.<br/>
    /// This account identifier MUST NOT use the alias field.<br/>
    /// If the identified account does not exist, this transaction SHALL fail.<br/>
    /// Multiple nodes MAY share the same node account.<br/>
    /// This field is REQUIRED.
    #[prost(message, optional, tag = "1")]
    pub account_id: ::core::option::Option<crate::services::AccountId>,
        /// A short description of the node.
    /// <p>
    /// This value, if set, MUST NOT exceed `transaction.maxMemoUtf8Bytes`
    /// (default 100) bytes when encoded as UTF-8.<br/>
    /// This field is OPTIONAL.
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
        /// A list of service endpoints for gossip.
    /// <p>
    /// These endpoints SHALL represent the published endpoints to which other
    /// consensus nodes may _gossip_ transactions.<br/>
    /// These endpoints MUST specify a port.<br/>
    /// This list MUST NOT be empty.<br/>
    /// This list MUST NOT contain more than `10` entries.<br/>
    /// The first two entries in this list SHALL be the endpoints published to
    /// all consensus nodes.<br/>
    /// All other entries SHALL be reserved for future use.
    /// <p>
    /// Each network may have additional requirements for these endpoints.
    /// A client MUST check network-specific documentation for those
    /// details.<br/>
    /// If the network configuration value `gossipFqdnRestricted` is set, then
    /// all endpoints in this list MUST supply only IP address.<br/>
    /// If the network configuration value `gossipFqdnRestricted` is _not_ set,
    /// then endpoints in this list MAY supply either IP address or FQDN, but
    /// MUST NOT supply both values for the same endpoint.
    #[prost(message, repeated, tag = "3")]
    pub gossip_endpoint: ::prost::alloc::vec::Vec<crate::services::ServiceEndpoint>,
        /// A list of service endpoints for gRPC calls.
    /// <p>
    /// These endpoints SHALL represent the published gRPC endpoints to which
    /// clients may submit transactions.<br/>
    /// These endpoints MUST specify a port.<br/>
    /// Endpoints in this list MAY supply either IP address or FQDN, but MUST
    /// NOT supply both values for the same endpoint.<br/>
    /// This list MUST NOT be empty.<br/>
    /// This list MUST NOT contain more than `8` entries.
    #[prost(message, repeated, tag = "4")]
    pub service_endpoint: ::prost::alloc::vec::Vec<crate::services::ServiceEndpoint>,
        /// A certificate used to sign gossip events.
    /// <p>
    /// This value MUST be a certificate of a type permitted for gossip
    /// signatures.<br/>
    /// This value MUST be the DER encoding of the certificate presented.<br/>
    /// This field is REQUIRED and MUST NOT be empty.
    #[prost(bytes = "vec", tag = "5")]
    pub gossip_ca_certificate: ::prost::alloc::vec::Vec<u8>,
        /// A hash of the node gRPC TLS certificate.
    /// <p>
    /// This value MAY be used to verify the certificate presented by the node
    /// during TLS negotiation for gRPC.<br/>
    /// This value MUST be a SHA-384 hash.<br/>
    /// The TLS certificate to be hashed MUST first be in PEM format and MUST be
    /// encoded with UTF-8 NFKD encoding to a stream of bytes provided to
    /// the hash algorithm.<br/>
    /// This field is OPTIONAL.
    #[prost(bytes = "vec", tag = "6")]
    pub grpc_certificate_hash: ::prost::alloc::vec::Vec<u8>,
        /// An administrative key controlled by the node operator.
    /// <p>
    /// This key MUST sign this transaction.<br/>
    /// This key MUST sign each transaction to update this node.<br/>
    /// This field MUST contain a valid `Key` value.<br/>
    /// This field is REQUIRED and MUST NOT be set to an empty `KeyList`.
    #[prost(message, optional, tag = "7")]
    pub admin_key: ::core::option::Option<crate::services::Key>,
        /// A boolean flag indicating whether the node operator declines to receive
    /// node rewards.
    /// <p>
    /// If this flag is set to `true`, the node operator declines to receive
    /// node rewards.<br/>
    #[prost(bool, tag = "8")]
    pub decline_reward: bool,
        /// A web proxy for gRPC from non-gRPC clients.
    /// <p>
    /// This endpoint SHALL be a Fully Qualified Domain Name (FQDN) using the HTTPS
    /// protocol, and SHALL support gRPC-Web for use by browser-based clients.<br/>
    /// This endpoint MUST be signed by a trusted certificate authority.<br/>
    /// This endpoint MUST use a valid port and SHALL be reachable over TLS.<br/>
    /// This field MAY be omitted if the node does not support gRPC-Web access.<br/>
    /// This field MUST be updated if the gRPC-Web endpoint changes.<br/>
    /// This field SHALL enable frontend clients to avoid hard-coded proxy endpoints.
    #[prost(message, optional, tag = "9")]
    pub grpc_proxy_endpoint: ::core::option::Option<crate::services::ServiceEndpoint>,
        /// A list of registered nodes operated by the same entity as this node.<br/>
    /// This value may contain a list of "registered nodes" (as described in
    /// HIP-1137) that are operated by the same entity that operates this
    /// consensus node.
    /// <p>
    /// This field is OPTIONAL and MAY be empty.<br/>
    /// This field MUST NOT contain more than twenty(20) entries.<br/>
    /// Every entry in this list MUST be a valid `registered_node_id` for a
    /// current registered node.
    #[prost(uint64, repeated, tag = "10")]
    pub associated_registered_node: ::prost::alloc::vec::Vec<u64>,
}
/// Transaction body to modify address book node attributes.
///
/// - This transaction SHALL enable the node operator, as identified by the
///    `admin_key`, to modify operational attributes of the node.
/// - This transaction MUST be signed by the active `admin_key` for the node.
/// - If this transaction sets a new value for the `admin_key`, then both the
///    current `admin_key`, and the new `admin_key` MUST sign this transaction.
/// - This transaction SHALL NOT change any field that is not set (is null) in
///    this transaction body.
/// - This SHALL create a pending update to the node, but the change SHALL NOT
///    be immediately applied to the active configuration.
/// - All pending node updates SHALL be applied to the active network
///    configuration during the next `freeze` transaction with the field
///    `freeze_type` set to `PREPARE_UPGRADE`.
///
/// ### Block Stream Effects
/// None.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeUpdateTransactionBody {
        /// A consensus node identifier in the network state.
    /// <p>
    /// The node identified MUST exist in the network address book.<br/>
    /// The node identified MUST NOT be deleted.<br/>
    /// This value is REQUIRED.
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
        /// An account identifier.
    /// <p>
    /// If set, this SHALL replace the node account identifier.<br/>
    /// If set, this transaction MUST be signed by the active `key` for _both_
    /// the current node account _and_ the identified new node account.
    #[prost(message, optional, tag = "2")]
    pub account_id: ::core::option::Option<crate::services::AccountId>,
        /// A short description of the node.
    /// <p>
    /// This value, if set, MUST NOT exceed `transaction.maxMemoUtf8Bytes`
    /// (default 100) bytes when encoded as UTF-8.<br/>
    /// If set, this value SHALL replace the previous value.
    #[prost(message, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
        /// A list of service endpoints for gossip.
    /// <p>
    /// If set, this list MUST meet the following requirements.
    /// <hr/>
    /// These endpoints SHALL represent the published endpoints to which other
    /// consensus nodes may _gossip_ transactions.<br/>
    /// These endpoints SHOULD NOT specify both address and DNS name.<br/>
    /// This list MUST NOT be empty.<br/>
    /// This list MUST NOT contain more than `10` entries.<br/>
    /// The first two entries in this list SHALL be the endpoints published to
    /// all consensus nodes.<br/>
    /// All other entries SHALL be reserved for future use.
    /// <p>
    /// Each network may have additional requirements for these endpoints.
    /// A client MUST check network-specific documentation for those
    /// details.<br/>
    /// <blockquote>Example<blockquote>
    /// Hedera Mainnet _requires_ that address be specified, and does not
    /// permit DNS name (FQDN) to be specified.
    /// </blockquote>
    /// <blockquote>
    /// Solo, however, _requires_ DNS name (FQDN) but also permits
    /// address.
    /// </blockquote></blockquote>
    /// <p>
    /// If set, the new list SHALL replace the existing list.
    #[prost(message, repeated, tag = "4")]
    pub gossip_endpoint: ::prost::alloc::vec::Vec<crate::services::ServiceEndpoint>,
        /// A list of service endpoints for gRPC calls.
    /// <p>
    /// If set, this list MUST meet the following requirements.
    /// <hr/>
    /// These endpoints SHALL represent the published endpoints to which clients
    /// may submit transactions.<br/>
    /// These endpoints SHOULD specify address and port.<br/>
    /// These endpoints MAY specify a DNS name.<br/>
    /// These endpoints SHOULD NOT specify both address and DNS name.<br/>
    /// This list MUST NOT be empty.<br/>
    /// This list MUST NOT contain more than `8` entries.
    /// <p>
    /// Each network may have additional requirements for these endpoints.
    /// A client MUST check network-specific documentation for those
    /// details.
    /// <p>
    /// If set, the new list SHALL replace the existing list.
    #[prost(message, repeated, tag = "5")]
    pub service_endpoint: ::prost::alloc::vec::Vec<crate::services::ServiceEndpoint>,
        /// A certificate used to sign gossip events.
    /// <p>
    /// This value MUST be a certificate of a type permitted for gossip
    /// signatures.<br/>
    /// This value MUST be the DER encoding of the certificate presented.
    /// <p>
    /// If set, the new value SHALL replace the existing bytes value.
    #[prost(message, optional, tag = "6")]
    pub gossip_ca_certificate: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
        /// A hash of the node gRPC TLS certificate.
    /// <p>
    /// This value MAY be used to verify the certificate presented by the node
    /// during TLS negotiation for gRPC.<br/>
    /// This value MUST be a SHA-384 hash.<br/>
    /// The TLS certificate to be hashed MUST first be in PEM format and MUST be
    /// encoded with UTF-8 NFKD encoding to a stream of bytes provided to
    /// the hash algorithm.<br/>
    /// <p>
    /// If set, the new value SHALL replace the existing hash value.
    #[prost(message, optional, tag = "7")]
    pub grpc_certificate_hash: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
        /// An administrative key controlled by the node operator.
    /// <p>
    /// This field is OPTIONAL.<br/>
    /// If set, this key MUST sign this transaction.<br/>
    /// If set, this key MUST sign each subsequent transaction to
    /// update this node.<br/>
    /// If set, this field MUST contain a valid `Key` value.<br/>
    /// If set, this field MUST NOT be set to an empty `KeyList`.
    #[prost(message, optional, tag = "8")]
    pub admin_key: ::core::option::Option<crate::services::Key>,
        /// A boolean indicating that this node has chosen to decline node rewards
    /// distributed at the end of staking period.
    /// <p>
    /// This node SHALL NOT receive reward if this value is set, and `true`.
    #[prost(message, optional, tag = "9")]
    pub decline_reward: ::core::option::Option<bool>,
        /// A web proxy for gRPC from non-gRPC clients.
    /// <p>
    /// This endpoint SHALL be a Fully Qualified Domain Name (FQDN) using the HTTPS
    /// protocol, and SHALL support gRPC-Web for use by browser-based clients.<br/>
    /// This endpoint MUST be signed by a trusted certificate authority.<br/>
    /// This endpoint MUST use a valid port and SHALL be reachable over TLS.<br/>
    /// This field MAY be omitted if the node does not support gRPC-Web access.<br/>
    /// This field MUST be updated if the gRPC-Web endpoint changes.<br/>
    /// This field SHALL enable frontend clients to avoid hard-coded proxy endpoints.<br/>
    /// This field MAY be set to `ServiceEndpoint.DEFAULT` to remove a previously-valid
    /// web proxy.
    #[prost(message, optional, tag = "10")]
    pub grpc_proxy_endpoint: ::core::option::Option<crate::services::ServiceEndpoint>,
        /// A list of registered nodes operated by the same entity as this node.<br/>
    /// This value may contain a list of "registered nodes" (as described in
    /// HIP-1137) that are operated by the same entity that operates this
    /// consensus node.
    /// <p>
    /// This field is OPTIONAL.<br/>
    /// If this field is not set, the current list SHALL NOT change.<br/>
    /// If this field is set, but contains an empty list, any existing
    /// associated registered nodes SHALL be removed.<br/>
    /// This field MUST NOT contain more than twenty(20) entries.<br/>
    /// Every entry in this list MUST be a valid `registered_node_id` for a
    /// current registered node.
    #[prost(message, optional, tag = "11")]
    pub associated_registered_node_list: ::core::option::Option<
        AssociatedRegisteredNodeList,
    >,
}
/// A wrapper around a list of associated registered node identifiers.<br/>
/// This wrapper exists to enable an update transaction to differentiate
/// between a field that is not set and an empty list of values.
/// <p>
/// An _unset_ field of this type SHALL NOT modify existing values.<br/>
/// A _set_ field of this type with an empty list SHALL remove any
/// existing values.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssociatedRegisteredNodeList {
        /// A list of registered node identifiers.
    #[prost(uint64, repeated, tag = "1")]
    pub associated_registered_node: ::prost::alloc::vec::Vec<u64>,
}
/// A transaction body to delete a node from the network address book.
///
/// - A `NodeDeleteTransactionBody` MUST be signed by one of those keys:
///    adminKey, treasure account (2) key, systemAdmin(50) key, or
///    addressBookAdmin(55) key.
/// - Upon success, the address book entry SHALL enter a "pending delete"
///    state.
/// - All address book entries pending deletion SHALL be removed from the
///    active network configuration during the next `freeze` transaction with
///    the field `freeze_type` set to `PREPARE_UPGRADE`.<br/>
/// - A deleted address book node SHALL be removed entirely from network state.
/// - A deleted address book node identifier SHALL NOT be reused.
///
/// ### Block Stream Effects
/// None.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct NodeDeleteTransactionBody {
        /// A consensus node identifier in the network state.
    /// <p>
    /// The node identified MUST exist in the network address book.<br/>
    /// The node identified MUST NOT be deleted.<br/>
    /// This value is REQUIRED.
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
}
/// A registered network node endpoint.<br/>
/// Each registered network node in the global address book publishes one or
/// more endpoints which enable the nodes to communicate both with other
/// nodes and with clients to receive requests.
///
/// This message supports a TCP/UDP port and IP address (V4 or V6),
/// or MAY include a FQDN _instead of_ an IP address.<br/>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisteredServiceEndpoint {
        /// A network port to use.
    /// <p>
    /// This value MUST be between 0 and 65535, inclusive.<br/>
    /// This value is REQUIRED.
    #[prost(uint32, tag = "3")]
    pub port: u32,
        /// A flag indicating if this endpoint requires TLS.
    /// <p>
    /// If this value is set true, then connections to this endpoint MUST
    /// enable TLS.
    /// <p>
    /// TLS endpoints MAY use self-signed certificates for this purpose,
    /// but use of self-signed certificates SHOULD be limited to testing and
    /// development environments to ensure production environments meet all
    /// expected characteristics for transport layer security.
    #[prost(bool, tag = "4")]
    pub requires_tls: bool,
        /// An IP address or fully qualified domain name.
    /// <p>
    /// This oneof is REQUIRED.
    #[prost(oneof = "registered_service_endpoint::Address", tags = "1, 2")]
    pub address: ::core::option::Option<registered_service_endpoint::Address>,
        /// An endpoint type.<br/>
    /// This declares the type of registered node endpoint and includes any
    /// type-specific fields.
    /// <p>
    /// This oneof is REQUIRED.
    #[prost(oneof = "registered_service_endpoint::EndpointType", tags = "5, 6, 7, 8")]
    pub endpoint_type: ::core::option::Option<registered_service_endpoint::EndpointType>,
}
/// Nested message and enum types in `RegisteredServiceEndpoint`.
pub mod registered_service_endpoint {
        /// A message indicating this endpoint is a Block Node endpoint.<br/>
    /// Block Node endpoints offer one of several block node APIs, so this
    /// endpoint entry also declares which well-known Block Node API is
    /// supported by this endpoint, or "OTHER" for less common APIs.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct BlockNodeEndpoint {
                /// An indicator of what API this endpoint supports.
        /// <p>
        /// This field is REQUIRED.
        #[prost(enumeration = "block_node_endpoint::BlockNodeApi", repeated, tag = "1")]
        pub endpoint_api: ::prost::alloc::vec::Vec<i32>,
    }
    /// Nested message and enum types in `BlockNodeEndpoint`.
    pub mod block_node_endpoint {
                /// An enumeration of well-known block node endpoint APIs, and a
        /// catch-all option for otherwise unknown endpoint APIs.
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum BlockNodeApi {
                        /// Any other API type associated with a block node.<br/>
            /// The caller must consult local documentation to determine the
            /// correct call semantics.<br/>
            /// It is RECOMMENDED to call the detail status endpoint for further
            /// information before using this endpoint.
            Other = 0,
                        /// The Block Node Status API.
            Status = 1,
                        /// The Block Node Publish API.
            Publish = 2,
                        /// The Block Node Subscribe Stream API.
            SubscribeStream = 3,
                        /// The Block Node State Proof API.
            StateProof = 4,
        }
        impl BlockNodeApi {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Self::Other => "OTHER",
                    Self::Status => "STATUS",
                    Self::Publish => "PUBLISH",
                    Self::SubscribeStream => "SUBSCRIBE_STREAM",
                    Self::StateProof => "STATE_PROOF",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "OTHER" => Some(Self::Other),
                    "STATUS" => Some(Self::Status),
                    "PUBLISH" => Some(Self::Publish),
                    "SUBSCRIBE_STREAM" => Some(Self::SubscribeStream),
                    "STATE_PROOF" => Some(Self::StateProof),
                    _ => None,
                }
            }
        }
    }
        /// A message indicating this endpoint is a Mirror Node endpoint.
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct MirrorNodeEndpoint {}
        /// A message indicating this endpoint is a RPC Relay endpoint.
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct RpcRelayEndpoint {}
        /// A message indicating this endpoint is a General Service endpoint.
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct GeneralServiceEndpoint {
                /// A short description of the service provided.
        /// <p>
        /// This value, if set, MUST NOT exceed 100 bytes when encoded as UTF-8.<br/>
        /// This field is OPTIONAL.
        #[prost(string, tag = "1")]
        pub description: ::prost::alloc::string::String,
    }
        /// An IP address or fully qualified domain name.
    /// <p>
    /// This oneof is REQUIRED.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Address {
                /// A 32-bit IPv4 address or 128-bit IPv6 address.<br/>
        /// This is the address of the endpoint, encoded in pure "big-endian"
        /// (i.e. left to right) order (e.g. IPv4 address `127.0.0.1` has
        /// hex bytes in the order `7F`, `00`, `00`, `01`.<br/>
        /// IPv6 address `::1` has hex bytes `00`, `00`, `00`, `00`, `00`, `00`,
        /// `00`, `00`, `00`, `00`, `00`, `00`, `00`, `00`, `00`, `01`).
        #[prost(bytes, tag = "1")]
        IpAddress(::prost::alloc::vec::Vec<u8>),
                /// A node domain name.
        /// <p>
        /// This MUST be the fully qualified domain name of the node.<br/>
        /// This value MUST NOT exceed 250 ASCII characters.<br/>
        /// This value MUST meet all other DNS name requirements.
        #[prost(string, tag = "2")]
        DomainName(::prost::alloc::string::String),
    }
        /// An endpoint type.<br/>
    /// This declares the type of registered node endpoint and includes any
    /// type-specific fields.
    /// <p>
    /// This oneof is REQUIRED.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum EndpointType {
                /// A Block Node.<br/>
        /// A Block Node stores the block chain, provides content proof services,
        /// and delivers the block stream to other clients.
        #[prost(message, tag = "5")]
        BlockNode(BlockNodeEndpoint),
                /// A Mirror Node.<br/>
        /// A Mirror Node is an advanced indexing and query service that provides
        /// fast and flexible access to query the block chain and transaction
        /// history. A Mirror Node typically stores all recent blockchain data,
        /// and some store the entire history of the network.
        #[prost(message, tag = "6")]
        MirrorNode(MirrorNodeEndpoint),
                /// A RPC Relay.<br/>
        /// A RPC Relay is a proxy and translator between EVM tooling and a
        /// Hiero consensus network.
        #[prost(message, tag = "7")]
        RpcRelay(RpcRelayEndpoint),
                /// A general service.<br/>
        /// A general service endpoint represents any network accessible service
        /// that is provided by a registered node but that is not a service
        /// currently defined as part of the Hiero Ledger system.
        #[prost(message, tag = "8")]
        GeneralService(GeneralServiceEndpoint),
    }
}
/// A transaction body to create a new registered node in the network
/// address book.
///
/// This transaction, once complete, SHALL add a new registered node to the
/// network state.
/// The new registered node SHALL be visible and discoverable upon
/// completion of this transaction.
///
/// ### Block Stream Effects
/// None.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisteredNodeCreateTransactionBody {
        /// An administrative key controlled by the node operator.
    /// <p>
    /// This key MUST sign this transaction.<br/>
    /// This key MUST sign each transaction to update this node.<br/>
    /// This field MUST contain a valid `Key` value.<br/>
    /// This field is REQUIRED and MUST NOT be set to an empty `KeyList`.<br/>
    /// It is RECOMMENDED that this key be composed of one or more unique public
    /// keys that are not associated with any network account.<br/>
    /// This key MAY be a complex key containing `KeyList` or `ThresholdKey`
    /// elements, but SHOULD NOT be a contract ID key.
    #[prost(message, optional, tag = "1")]
    pub admin_key: ::core::option::Option<crate::services::Key>,
        /// A short description of the node.
    /// <p>
    /// This value, if set, MUST NOT exceed 100 bytes when encoded as UTF-8.<br/>
    /// This field is OPTIONAL.
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
        /// A list of service endpoints for client calls.
    /// <p>
    /// These endpoints SHALL represent the published endpoints to which
    /// clients may submit requests.<br/>
    /// Endpoints in this list MAY supply either IP address or FQDN, but MUST
    /// NOT supply both values for the same endpoint.<br/>
    /// Multiple endpoints in this list MAY resolve to the same interface.<br/>
    /// One Registered Node MAY expose endpoints for multiple service types.<br/>
    /// This list MUST NOT be empty.<br/>
    /// This list MUST NOT contain more than `50` entries.
    #[prost(message, repeated, tag = "3")]
    pub service_endpoint: ::prost::alloc::vec::Vec<RegisteredServiceEndpoint>,
}
/// A transaction body to update an existing registered node in the network
/// address book.
///
/// This transaction, once complete, SHALL modify the identified registered
/// node state as requested.
///
/// ### Block Stream Effects
/// None.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisteredNodeUpdateTransactionBody {
        /// A registered node identifier in the network state.
    /// <p>
    /// The node identified MUST exist in the registered address book.<br/>
    /// The node identified MUST NOT be deleted.<br/>
    /// This value is REQUIRED.
    /// <p>
    /// A given value for `registered_node_id` SHALL be unique within a given
    /// shard or realm.<br/>
    /// A given value for `registered_node_id` SHALL NOT be reused, even if the
    /// corresponding entry is deleted.
    #[prost(uint64, tag = "1")]
    pub registered_node_id: u64,
        /// An administrative key controlled by the node operator.
    /// <p>
    /// This field is OPTIONAL.<br/>
    /// If set, this key MUST sign this transaction.<br/>
    /// If set, this key MUST sign each subsequent transaction to
    /// update this node.<br/>
    /// If set, this field MUST contain a valid `Key` value.<br/>
    /// If set, this field MUST NOT be set to an empty `KeyList`.<br/>
    /// It is RECOMMENDED that this key be composed of one or more unique public
    /// keys that are not associated with any network account.<br/>
    /// This key MAY be a complex key containing `KeyList` or `ThresholdKey`
    /// elements, but SHOULD NOT be a contract ID key.
    #[prost(message, optional, tag = "2")]
    pub admin_key: ::core::option::Option<crate::services::Key>,
        /// A short description of the node.
    /// <p>
    /// This field is OPTIONAL.<br/>
    /// This value, if set, MUST NOT exceed 100 bytes when encoded as UTF-8.<br/>
    /// If set, this value SHALL replace the previous value.
    #[prost(message, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
        /// A list of service endpoints for client calls.
    /// <p>
    /// This field is OPTIONAL.<br/>
    /// These endpoints SHALL represent the published endpoints to which
    /// clients may submit requests.<br/>
    /// Endpoints in this list MAY supply either IP address or FQDN, but MUST
    /// NOT supply both values for the same endpoint.<br/>
    /// One Registered Node MAY expose endpoints for multiple service types.<br/>
    /// If set, this list MUST NOT be empty.<br/>
    /// If set, this list MUST NOT contain more than `50` entries.<br/>
    /// If set, this list SHALL _replace_ the previous list.
    #[prost(message, repeated, tag = "4")]
    pub service_endpoint: ::prost::alloc::vec::Vec<RegisteredServiceEndpoint>,
}
/// A transaction body to delete a registered node from the network
/// address book.
///
/// This transaction, once complete, SHALL remove the identified registered
/// node from the network state.
/// This transaction MUST be signed by the existing entry `admin_key` or
/// authorized by the Hiero network governance structure.
///
/// ### Block Stream Effects
/// None.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RegisteredNodeDeleteTransactionBody {
        /// A registered node identifier in the network state.
    /// <p>
    /// The node identified MUST exist in the registered address book.<br/>
    /// The node identified MUST NOT be deleted.<br/>
    /// This value is REQUIRED.
    /// <p>
    /// A given value for `registered_node_id` SHALL be unique within a given
    /// shard or realm.<br/>
    /// A given value for `registered_node_id` SHALL NOT be reused, even if the
    /// corresponding entry is deleted.
    #[prost(uint64, tag = "1")]
    pub registered_node_id: u64,
}
/// A system initiated transaction to externalize the ledger id and verification
/// key for recursive chain-of-trust proofs extending from the new ledger id.
///
/// This transaction SHALL be issued whenever the ledger id changes.<br/>
/// This transaction MUST NOT be sent by a client and SHALL be rejected if
/// received by any node.<br/>
/// This transaction SHALL be present in the record stream or block stream.
///
/// ### Block Stream Effects
/// None
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LedgerIdPublicationTransactionBody {
        /// The new ledger id.
    #[prost(bytes = "vec", tag = "1")]
    pub ledger_id: ::prost::alloc::vec::Vec<u8>,
        /// The key to use when verifying recursive chain-of-trust proofs that extend
    /// from this ledger id.
    #[prost(bytes = "vec", tag = "2")]
    pub history_proof_verification_key: ::prost::alloc::vec::Vec<u8>,
        /// The node-specific contributions made to the new ledger id.
    #[prost(message, repeated, tag = "3")]
    pub node_contributions: ::prost::alloc::vec::Vec<LedgerIdNodeContribution>,
}
/// A record of the proof key a node had in a particular address
/// book. Necessary to keep at each point history so that nodes
/// can verify the correct key was used to sign in transitions
/// starting from the current address book; no matter how keys
/// have been rotated from the time the address book was created.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LedgerIdNodeContribution {
        /// The node id.
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
        /// The node's consensus weight when the ledger id was published.
    #[prost(uint64, tag = "2")]
    pub weight: u64,
        /// The public key the node used to contribute to history proofs when the
    /// ledger id was published.
    #[prost(bytes = "vec", tag = "3")]
    pub history_proof_key: ::prost::alloc::vec::Vec<u8>,
}
/// Adds or removes key/value pairs in the storage of an EVM hook.
/// Either the hook owner's key, or its admin key, must sign the transaction.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HookStoreTransactionBody {
        /// The id of the EVM hook whose storage is being updated.
    #[prost(message, optional, tag = "1")]
    pub hook_id: ::core::option::Option<HookId>,
        /// The updates to the storage of the EVM hook.
    #[prost(message, repeated, tag = "2")]
    pub storage_updates: ::prost::alloc::vec::Vec<EvmHookStorageUpdate>,
}
/// Dispatches a hook action to an appropriate service.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HookDispatchTransactionBody {
    #[prost(oneof = "hook_dispatch_transaction_body::Action", tags = "1, 2, 3")]
    pub action: ::core::option::Option<hook_dispatch_transaction_body::Action>,
}
/// Nested message and enum types in `HookDispatchTransactionBody`.
pub mod hook_dispatch_transaction_body {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Action {
                /// The id of the hook to delete.
        #[prost(message, tag = "1")]
        HookIdToDelete(super::HookId),
                /// Creation details for a new hook.
        #[prost(message, tag = "2")]
        Creation(super::HookCreation),
                /// Execution details of an existing hook.
        #[prost(message, tag = "3")]
        Execution(super::HookExecution),
    }
}
/// Details the execution of a hook.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HookExecution {
        /// The id of the hook's entity.
    #[prost(message, optional, tag = "1")]
    pub hook_entity_id: ::core::option::Option<HookEntityId>,
        /// The details of the call, including which hook id to call.
    #[prost(message, optional, tag = "2")]
    pub call: ::core::option::Option<HookCall>,
}
/// A transaction body for handling a set of transactions atomically.
///
/// <<<pbj.java_package = "com.hedera.hapi.node.util">>> This comment is special code for setting PBJ Compiler java package
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AtomicBatchTransactionBody {
        /// A list of signed bytes that represent the batch transactions.
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// A simple protobuf wrapper to store a list of transactions. This is used by
/// `Transaction.\[from|to\]Bytes()` in the SDKs. The reason the SDK needs a list of transactions is
/// because it holds onto a transaction per node. So if a transaction is to be submitted to nodes 3
/// and 4 the SDK Transaction type would contain a list of 2 protobuf transactions, one for node 3
/// and one for node 4.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionList {
    #[prost(message, repeated, tag = "1")]
    pub transaction_list: ::prost::alloc::vec::Vec<crate::services::Transaction>,
}
