// This file is @generated by prost-build.
/// A simple protobuf wrapper to store a list of transactions. This is used by
/// `Transaction.[from|to]Bytes()` in the SDKs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionList {
    #[prost(message, repeated, tag = "1")]
    pub transaction_list: ::prost::alloc::vec::Vec<crate::services::Transaction>,
}
