[package]
name = "anychain-neo-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anychain-core = { path = "../../crates/anychain-core" }
anychain-neo = { path = "../../crates/anychain-neo" }
clap = { workspace = true }
