[package]
name = "anychain-polkadot"
version = "0.1.0"
edition = "2021"

[dependencies]
anychain-core = { path = "../anychain-core", version = "0.1.1" }
blake2b_simd = "1.0.2"
ed25519-dalek-fiat = "0.1.0"
