[package]
name = "anychain-polkadot"
version = "0.1.0"
edition = "2021"

[dependencies]
anychain-core = { path = "../anychain-core", version = "0.1.1" }
sp-core = "24.0.0"
base58 = { workspace = true }
parity-scale-codec = "3.6.5"
ed25519-dalek-fiat = "0.1.0"