name: Audit Matchine CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


env:
  CI: true
  AUDIT_SERVER: "https://api.sguard.top"    # 1
  PROJECT_NAME: "${{ github.repository }}"  # 2

jobs:
  security-audit: # 3
    name: "code audit"
    runs-on: [ self-hosted, audit-machine ]
    timeout-minutes: 180  #

    steps:
      - name: "checkout code"
        uses: actions/checkout@v4

      - name: "run security scan"
        run: |
          echo "SAST scan..."
          # Semgrep scan 
          SEMGREP_REDACT_CODE=true semgrep scan --config auto . 2>&1 | tee semgrep_report.txt

      - name: "upload scan results"
        run: |
          echo "upload scan results..."
          curl -X POST "$AUDIT_SERVER/upload-and-audit/" \
            -F "file=@semgrep_report.txt" \
            -F "additional_param=$PROJECT_NAME" \
            -o uploadResponse.json
          UPLOAD_RESPONSE=$(cat uploadResponse.json)
          echo "semgrep upload file API response: $UPLOAD_RESPONSE"  

      - name: "poll audit results"

        id: audit-result
        run: |
          echo "poll audit results..."
          
          for i in {1..100}; do
            echo "polling attempt $i..."
          
            curl -X POST "$AUDIT_SERVER/audit-status/" \
              -F "task_id=$PROJECT_NAME" \
              -o auditResponse.json
          
            AUDIT_RESPONSE=$(cat auditResponse.json)
            echo "audit result status: $AUDIT_RESPONSE"
          
            STATUS=$(jq -r '.status // "error"' auditResponse.json 2>/dev/null || echo "error")
          
            if [ "$STATUS" = "completed" ]; then
              echo "✅ Audit completed"
              exit 0
            elif [ "$STATUS" = "failed" ]; then
              echo "Audit failed, please check the audit server for details."
              exit 1     #
            fi
          
            sleep 60
          done
          echo "❌ Polling timed out"
          exit 1

  quality:
    name: Quality
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: security-audit                               # 4
    if: needs.security-audit.result == 'success'        # 5

    strategy:
      matrix:
        rust-version: [ 1.98.0 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: cargo clippy
        run: cargo clippy --workspace --all-targets --tests -- -D warnings

      - name: Build and test
        run: cargo test --all-features